@startuml sequenceSolver
actor QueryEngine as comunicaActor
alt The TREE relation has an expression
comunicaActor -> TREEDocumentParser: Send TREE relation
else The TREE relation has no condition
TREEDocumentParser --> comunicaActor: Indicate that the node must be follow
end
comunicaActor -> SPARQLFilterParser: Send the SPARQL filter expression
TREEDocumentParser -> Solver: Send TREE relation boolean expression
SPARQLFilterParser -> Solver: Send the relevant SPARQL filter boolean expression
alt The types are compatible
Solver->Solver: Calculate The solution domain of the SPARQL filter boolean expression
Solver -> Solver: Calculate the solution domain of the TREE relation and the filter
Solver -> comunicaActor: Indicate if the node must be follow
else The types are not compatible 
Solver --> comunicaActor: Indicate that the solver cannot resolved the equation
end
@enduml